plugins { id 'com.android.application' }

android {
    namespace 'io.github.matrixneo23.tessagptinarelay'
    compileSdk 35

    defaultConfig {
        applicationId 'io.github.matrixneo23.tessagptinarelay'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '0.2-vertical'
    }
}
